---
format: "html"
---

First of all, [Welcome to the Applied AI Bootcamp!](./lessons/01_bootcamp_intro.qmd).

## Module 1: Setup

1. [Terminal: Shell Basics](./lessons/02_shell.qmd)
2. [IDE: VS Code Basics](./lessons/03_vs_code.qmd)
3. [Version Control: Git and GitHub](./lessons/04_source_control.qmd)

## Module 2: Syntax and Procedural Semantics

1. [Scripting](https://halgoz.quarto.pub/pythonia/content/01_instructions.html)
2. [Control Flow](https://halgoz.quarto.pub/pythonia/content/02_control_flow.html)
3. [Functions](https://halgoz.quarto.pub/pythonia/content/03_functions.html)

Exercises from [The Python Complete Exercise Notebook](./exercises/python_complete_quiz.ipynb):

- 1. Programming as a Way of Thinking
- 2. Variables and Statements
- 3. Functions
- 5. Conditionals and Recursion
- 6. Return Values

## Module 3: Working with Data Structures

4. [Sequencing](https://halgoz.quarto.pub/pythonia/content/04_sequences.html)
5. [Computer and the world](https://halgoz.quarto.pub/pythonia/content/05_computer_and_world.html)
6. [Text files](https://halgoz.quarto.pub/pythonia/content/06_text_files.html)
7. [Iteration](https://halgoz.quarto.pub/pythonia/content/07_iterators.html)

Exercises from [The Python Complete Exercise Notebook](./exercises/python_complete_quiz.ipynb):

- 7. Iteration and Search
- 8. Strings and Regular Expressions
- 9. Lists
- 10. Dictionaries
- 11. Tuples
- 13. Files

## Module 4: Programming Paradigms

8. [Object-oriented programming](https://halgoz.quarto.pub/pythonia/content/08_oop.html)
9. [Functional programming](https://halgoz.quarto.pub/pythonia/content/09_functional.html)
10. [Error](https://halgoz.quarto.pub/pythonia/content/10_errors.html)

Exercises from [The Python Complete Exercise Notebook](./exercises/python_complete_quiz.ipynb):

- 14. Classes and Functions
- 15. Classes and Methods
- 16. Classes and Objects
- 17. Inheritance

## Worked Examples and Exercises

| Examples | Problems | Solutions |
| :--- | :--- | :--- |
| [Numbers](https://halgoz.quarto.pub/pythonia/exercises/01_numbers/apps.html) | [Problems](https://halgoz.quarto.pub/pythonia/exercises/01_numbers/problems.html) | [Solutions](https://halgoz.quarto.pub/pythonia/exercises/01_numbers/solutions.html) |
| [Control Flow](https://halgoz.quarto.pub/pythonia/exercises/02_control_flow/apps.html) | [Problems](https://halgoz.quarto.pub/pythonia/exercises/02_control_flow/problems.html) | [Solutions](https://halgoz.quarto.pub/pythonia/exercises/02_control_flow/solutions.html) |
| [Sequencing](https://halgoz.quarto.pub/pythonia/exercises/03_sequences/apps.html) | [Problems](https://halgoz.quarto.pub/pythonia/exercises/03_sequences/problems.html) | [Solutions](https://halgoz.quarto.pub/pythonia/exercises/03_sequences/solutions.html) |
| [Dictionary](https://halgoz.quarto.pub/pythonia/exercises/04_mapping/apps.html) | [Problems](https://halgoz.quarto.pub/pythonia/exercises/04_mapping/problems.html) | — |
| [Procedural](https://halgoz.quarto.pub/pythonia/exercises/05_procedural/apps.html) | [Problems](https://halgoz.quarto.pub/pythonia/exercises/05_procedural/problems.html) | [Solutions](https://halgoz.quarto.pub/pythonia/exercises/05_procedural/solutions.html) |

## Final Problems

1. [List and Dict Access](https://halgoz.quarto.pub/pythonia/exercises/indexing_problems.html)
2. [Ceasar Cipher](https://halgoz.quarto.pub/pythonia/exercises/ceasar_cipher_problem.html)
3. [Reading docs: random](https://halgoz.quarto.pub/pythonia/exercises/docs_random_problem.html)
4. [Requests to APIs](https://halgoz.quarto.pub/pythonia/exercises/requests_ex.html)
